---
abstract: ' module to parse and generate ARNs'
author:
  - 'James Wright <jwright@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: '0.034'
  perl: '5.006'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.028, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AWS-ARN
provides:
  AWS::ARN:
    file: lib/AWS/ARN.pm
    version: '0.008'
requires:
  Moo: '2.0'
  Try::Tiny: '0'
  Type::Utils: '0'
  Types::Standard: '0'
resources:
  IRC: irc://irc.styxnet.tech/#perl
  bugtracker: https://github.com/tehmoth/AWS-ARN/issues
  repository: https://github.com/tehmoth/AWS-ARN.git
version: '0.007'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
